# --- OTel Collector ConfigMap ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: sre-project
data:
  otel-collector-config.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: otel
      otlp/jaeger:
        endpoint: "jaeger:4317"
        tls:
          insecure: true
      debug:
        verbosity: detailed
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger, debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, debug]
---
# --- OTel Collector Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: sre-project
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:0.103.0
        args: ["--config=/etc/otel-collector-config.yml"]
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 8889
          name: prometheus
        volumeMounts:
        - name: config
          mountPath: /etc/otel-collector-config.yml
          subPath: otel-collector-config.yml
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
---
# --- OTel Collector Service ---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: sre-project
spec:
  type: ClusterIP
  ports:
  - port: 4317
    targetPort: 4317
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    name: otlp-http
  - port: 8889
    targetPort: 8889
    name: prometheus
  selector:
    app: otel-collector
