apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: sre-project
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
      - name: traffic-generator
        image: sreprojectacr.azurecr.io/traffic-generator:latest
        env:
        - name: ORDER_SERVICE_URL
          value: "http://order-service:8080"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
